[package]
name = "mutable-bson"
version = "0.1.0"
edition = "2024"

[dependencies]
bson = "2.14.0"
bytes = "1.10.1"
indexmap = "2.8.0"
itoa = "1.0.15"
serde = { version = "1.0.219", features = ["derive"] }
